### ISSUE TITLE
add images for each "resource"

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#101]
![image](https://user-images.githubusercontent.com/2166159/225404830-1e6a0244-3c70-4795-a0d1-81bc7ebb4d69.png)

**Comment by mukteshkrmishra** [comment]
Let me share the mockup for this @davidstanke

**Comment by mukteshkrmishra** [comment]
Hi @davidstanke " While trying to run `hugo serve -D -s hugo --disableFastRender --debug --watch.` I keep getting error "failed to extract shortcode" for `[hugo/reser.](https://github.com/dora-team/dora.dev/blob/main/hugo/content/research/_index.md)` 

This is based on instructions from : https://github.com/dora-team/dora.dev/tree/main/docs Any pointers?

**Comment by mukteshkrmishra** [comment]
Current design : @davidstanke 
<img width="2446" alt="Screenshot 2023-04-10 at 4 29 23 PM" src="https://user-images.githubusercontent.com/10970467/231018522-ad8bad07-e65b-432f-9621-c1204b9d7363.png">

**Comment by mukteshkrmishra** [comment]
Another one with Fourkeys vertical Logo : 
<img width="2449" alt="Screenshot 2023-04-10 at 4 36 47 PM" src="https://user-images.githubusercontent.com/10970467/231019165-2572f47e-7dde-4063-895f-f7f6d6cd434c.png">

**Comment by davidstanke** [comment]
Nice! I prefer the second four keys logo option. Also, I suggest we bring the title and subtitle of each item down below the image. We also may want to add a bit of space between items to disambiguate. Please implement! 😀 We can do any final design tweaks in code.
