### ISSUE TITLE
2021 & 2022 Quick check always produces the same recommendation regardless of chosen answers

### ISSUE THREAD

**Issue by jjwils** [dora-team/dora.dev#144]
You are always recommended - **_Continuous Integration, Loosely Coupled Architecture, and Generative Organizational Culture_**. as areas for improvement no matter the answers you give to the quick check multiple choice questions.

2019 behaves as expected.

**Comment by davidstanke** [comment]
Hi @jjwils -- thanks for checking out the new site! Your observation is correct. :) For the new version of the quick check we've changed the capabilities for deeper assessment. It was always coarse-grained—_every team has a unique path!_—but we used to offer different sets of capabilities to assess depending on your performance cluster.

With the [removal of performance clusters](https://dora.dev/faq/) from the quick check results, we've switched to offering three capabilities that we've found are often beneficial for teams at all performance levels.

We will continue to iterate on the quick check, and we hope to offer tools that will be increasingly sensitive to the individual context of the teams using them.
