### ISSUE TITLE
Add a nightly build

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#164]
Let's do a nightly build-and-deploy from `main` to prod. That will help with early detection of delivery issues, on days when there aren't any code changes (there aren't any days like that right now, but things will likely slow down!)

**Comment by mukteshkrmishra** [comment]
Are we working on this?

**Comment by davidstanke** [comment]
Hi @mukteshkrmishra! I do intend to do this, but it'll have to be done by an administrator since that configuration happens on our Google Cloud project (we use Google Cloud Build for CI/CD). I'll assign to me. :)
