### ISSUE TITLE
Standardize case of capability titles

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#168]
There is a mix of cases...
<img width="292" alt="image" src="https://user-images.githubusercontent.com/2166159/229149476-c2f04ec9-8d72-4a76-9dba-42c148192156.png">

@michelleirvine what do you advise as a standard?

**Comment by mukteshkrmishra** [comment]
@davidstanke : I can work on this

**Comment by davidstanke** [comment]
Sweet! Assigned.

**Comment by mukteshkrmishra** [comment]
Also is there a slack channel?

**Comment by davidstanke** [comment]
>  Also is there a slack channel?

There is not a slack channel... there could be? Let me think on that. I'm all for having open communication but a little anxious about my ability to keep up with that as an added forum. 😬

One thing we do have is the discussions tab on this repo... would that be useful?

**Comment by mukteshkrmishra** [comment]
@davidstanke : Slack can be tricky especially since you brought the availability question. Albeit I still think we can benefit from each other :)  For the discussion tab, that wil be a good idea. Or we can create a project assign this repo there and track everything via github provided Kanban board :)

**Comment by mukteshkrmishra** [comment]
@davidstanke : Shall we close this?

**Comment by davidstanke** [comment]
Ah, good call... yes, this issue turned into a little discussion of its own, huh?

Let's start with: I'll open a Project that we can use to track work, and we can use Discussions for async conversations. If we find that we need more, we can add a Slack.
