### ISSUE TITLE
Close popovers on click outside popover

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#19]
Currently, when a popover is open, the only way to close it is to click on the "x" button. Better UX would be to close the popovers on any click outside the popover.

**Comment by jessegduke** [comment]
@davidstanke - I only see this issue in the 2019 user flows (3 occurrences).  Can you confirm?

**Comment by davidstanke** [comment]
That may be the only one at the moment (apologies I should have specified when I opened the bug!) ... but there are places that could be refactored: one that comes to mind is the hamburger menu on small screens; another is the forthcoming interactive BFD (#181)

**Comment by jessegduke** [comment]
Thanks.  I refactored 2019 under the new branch (19-).  AlpineJS makes this _very_ easy for 2 of the 3 occurrences.   However, for the third (QuickCheck - Help me prioritize) modal I want to think how we might use Templates w/ Alpine for the QuickCheck; I am hopeful.

**Comment by davidstanke** [comment]
Sweet! That templates project sounds interesting but out of scope for now. I suggest you open a new issue for that, and open a PR for the parts you've achieved (I looked at your branch and it looks solid)

**Comment by davidstanke** [comment]
Fixed by #192
