### ISSUE TITLE
Incorrect messaging of 2019 DORA DevOps Quick Check results to clipboard

### ISSUE THREAD

**Issue by jessegduke** [dora-team/dora.dev#194]
In the 2019 Share Results modal window, the text reads as the following:

`We've copied the URL to your DORA DevOps Quick Check results to your clipboard. Share via social media, email or chat.`

However, this copy to clipboard is not attempted.  We should either change the text or copy to clipboard.  Considering this feature is not present in other yearly comparisons, I recommend we change the text to something like 

`We have created the URL to your DORA DevOps Quick Check below.  Copy and share via social media, email or chat.`

**Comment by davidstanke** [comment]
+1! Auto-copying is inherently flaky IMHO. Your proposal is cleaner.
