### ISSUE TITLE
mispositioned `x` on quickcheck 2019

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#214]
The "x" button should be in the upper right of the modal:
![image](https://user-images.githubusercontent.com/2166159/231815171-d38334b0-3aff-48d0-a333-4a5b66d7e9fc.png)

...this is likely a result of the refactored modal styles introduced in #187

**Comment by jessegduke** [comment]
@davidstanke - If you want a quick fix, assign to me and I can update the 2019_css with the appropriate Style.  Otherwise, let me know if you would rather take a more holistic approach in another scss. - J

**Comment by davidstanke** [comment]
@jessegduke that'd be great--no need for holistic (good question though); the reason that unique stylesheet exists is so we can isolate the historic 2019 UI and not have to accommodate for it going forward.
