### ISSUE TITLE
Platform Maintenance: Release history

### ISSUE THREAD

**Issue by jessegduke** [dora-team/dora.dev#224]
Currently, it does not appear that the [Release history](https://firebase.google.com/docs/hosting/manage-hosting-resources#release-storage-settings) is being managed with the **_Release storage settings_** settings.  Therefore, the size is growing with each deployment

![image](https://user-images.githubusercontent.com/2676030/234268162-d1bf16f8-6ebf-4331-b3ca-a6a526c8f185.png)

Recommend setting the value to something like 3+/- to assist in storage consumption for both:
- doradotdev 
- draft-dora-dev 

This is a admin console setting; No development branch needed currently

**Comment by davidstanke** [comment]
Thank you for flagging that, @jessegduke! I've updated that setting to preserve 3 releases for each of the sites.
