### ISSUE TITLE
Clarify quick check language

### ISSUE THREAD

**Issue by nathenharvey** [dora-team/dora.dev#258]
The guidance after prioritizing capabilities:  
"These are only three of the capabilities that our research has shown to predict software delivery and operations performance. Here are some resources to help you plan the next step of your DevOps journey:"

Can, relatively easily, be misread as:   
"_There_ are only three ~of the~ capabilities that our research has shown to predict software delivery and operations performance. Here are some resources to help you plan the next step of your DevOps journey:"

Suggested change:

Our research has shown that many capabilities predict software delivery and operations performance. Here are some resources to help you plan the next step of your DevOps journey:

**Comment by davidstanke** [comment]
Cleanup: I'm closing all issues relating to pre-2023 Quick Check
