### ISSUE TITLE
Update Trigger Email extension

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#279]
_after_ #81 is fully landed, let's update to the newest version of [Trigger Email Extension](https://console.firebase.google.com/u/0/project/doradotdev/extensions/instances/firestore-send-email?tab=config). ... we can test it on staging and then roll out to prod if/when it works as intended.

**Comment by jessegduke** [comment]
@davidstanke - I feel we can address via Admin console. I've tested in my sandbox.  If you want, assign to me and I will knock it out in staging - then prod.

**Comment by jessegduke** [comment]
@davidstanke - Assigned to myself.  Updated Staging on 7/21.  Will hold on Production update until you approve. (Due to code bug in extension (issue #292 ) this will be a GUI update.
