### ISSUE TITLE
Add links to DORA blogs on c.g.c

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#338]
Over the past few years, the SODR authors have written some good posts on the Google Cloud blog. Many of them contain additional analyses/interpretations, beyond what is reported in SODR. Let's help these have continued discoverability by linking to them from DORA.dev. That can happen on the Resources page, and/or the research archives pages.

**Comment by nathenharvey** [comment]
https://github.com/dora-team/dora.dev/issues/291 was closed.  Is there more to do here?
