### ISSUE TITLE
Core - fix behavior of download links

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#353]
These links say "Download" but really the action that results from clicking is "view in new tab." Let's make them actual downloads: 

![image](https://github.com/dora-team/dora.dev/assets/2166159/23479f92-ed64-4258-b30c-80e9f63fab6b)

**Comment by Aneal07** [comment]
Could you assign this to me so I can fix this? please?

**Comment by davidstanke** [comment]
Fantastic -- go for it!

**Comment by davidstanke** [comment]
This was fixed by #357
