### ISSUE TITLE
Retire Remote Config

### ISSUE THREAD

**Issue by jessegduke** [dora-team/dora.dev#367]
After some work with Firebase Remote Config, I have come to the conclusion that it is "more powerful" than we need and creates some maintenance/management load that is not necessary.

I propose we retire the use of Firebase Remote Config and [leverage standard environment variables](https://firebase.google.com/docs/functions/config-env?gen=2nd#env-variables).  This will create easier resources to manage - both at prod run-time and developer experience.

**Comment by davidstanke** [comment]
Sounds like a smart refactor!
