### ISSUE TITLE
Accelerate State of DevOps Report Eratta

### ISSUE THREAD

**Issue by nathenharvey** [dora-team/dora.dev#375]
Create a landing page for submitting and reading eratta for the Accelerate State of DevOps Reports.

A form should be available to submit changes, corrections, and clarifications.  The form should include options for specifying the report year and version as well as the proposed change.

Changes that are agreed to should be published on this page, organized by year of the report.

**Comment by davidstanke** [comment]
Let's go with:

`https://dora.dev/publications/errata`
_and_
`https://dora.dev/research/<year>/dora-report/errata`

...we can invoke the power of Hugo to roll up the former from the contents of the latter
