### ISSUE TITLE
Create an interactive, search experience

### ISSUE THREAD

**Issue by jessegduke** [dora-team/dora.dev#396]
**_Concept Experiment_** 

With GCP's ability to create with ease a Generative AI Search experience with Gen App Enterprise Search, interested site visitors can have a dynamic, chat like experience based upon content hosted within the dora.dev site.

- Initially deploy under Hugo Draft
- After some validation, deploy to Production with language to communicate  _"experiment"_ experience to the end user

**Comment by davidstanke** [comment]
@swansama has been exploring Enterprise Search as well!

**Comment by jessegduke** [comment]
Excellent!  

@swansama -- We can talk about it next week at DOES, but let me know how I can help (if needed).  I just completed my Capstone as a Gen AI Specialist and I played with a few options (Web Standard, Web Advanced, and Vertex - I even used DORA public PDFs as my Vertex Notebook :) ) in my sandbox.  Happy to support you if needed!
