### ISSUE TITLE
Change "Time to Restore" metric to "Failed Deployment Recovery Time"

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#449]
On the Core diagram, and the modal about performance metrics, the fourth metric is called "Time to Restore." Per 2023 research, we should update this to "Failed Deployment Recovery Time"

**Comment by stevemcghee** [comment]
What are we changing apart from the name?

**Comment by davidstanke** [comment]
> What are we changing apart from the name?

Just the name and the brief description:

**Time to restore service:** How long does it generally take to restore service when a service incident or a defect that impacts users occurs (e.g., unplanned outage, service impairment)?

--> 

**Failed deployment recovery time:** How long does it generally take to restore service after a change to production or release to users results in degraded service?

**Comment by stevemcghee** [comment]
So we are further from TTR this folks are less likely to prepend an "M" which I like :) 

However, the meaning is still the same? We are asking people to issue a single value to a potentially highly variant set of incidents. 

Is such a lossy value *ever* meaningful?  I'm just being a 😈 advocate.

**Comment by nathenharvey** [comment]
Similar to all of the four measures, we are asking folks to share their lived experience across many highly variable set of events. Less variability, more regular cadence are, generally, viewed as better.

There is still an opportunity for lots of variability, bias, and inaccurate reporting.

We attempt to counteract some of these negative effects by looking at all four measures as a set without focusing too much on any one of them.

The refined wording in the 2023 survey did change what we're measuring though it's impossible to say how it effected the interpretation of what we're asking.  We did ask the question two ways in 2023 and saw differences between the new way and the more traditional way so there is reason to believe that we've actually changed what is being measured.

I'm in strong favor of the 2023 version of the Quick Check mirroring what was asked in the 2023 survey.

I'm open to accelerating a change to the core model, loosening the "must be investigated at least twice" criterion here.  Strong arguments can be made either way though.  This updated language is a better reflection of the spirit of the research and does clarify how a team might go about assessing and measuring the recovery time for their service.  I think that the clarification outweighs the potential that the data will reveal something dramatically different in future years.

**Comment by davidstanke** [comment]
Thanks all for the discussion! I think we have a consensus that we should reflect further on this, which we can do as part of our next scheduled update to Core in early 2024

**Comment by Winael** [comment]
Hi Everyone,

I don't understand this change. 

For many teams that are working on statefull architecture VM based, where ops often fix an incident on production directly on the VM (so you can't predict the real state of the VM), TTR is very usefull to help them to understand the advantage of IaC, CI, control version, etc... 

Failed Deployment Recovey Time seems to suggest that incident appears only after a failed deployment and you're mature enought to fix the code and redeploy it.

So yeah, TTR can have a big variability between old fashion ops operations (SSH to the VM and fixing it doing some stuff at 3 AM on duty call) and new fashion ops operations (IaC to Kubernetes with a stateless arch), but I think it's the point for this metrics, isn't it ?

Regards

**Comment by steve-fenton-octopus** [comment]
There are two distinct things we might want to measure. We certainly want to look at our production incidents, learn from them, and improve things continuously.

For *software delivery performance*, we want to filter down to incidents caused by our changes, not those that visit us late one night when a server rack self-ignites in a data center.

If you look at *both* faults caused by deliberate actions (code changes, deployments) *and* those random acts of nature, the signal gets drowned out. It doesn't make sense to measure *software delivery performance* on the time it takes an cloud vendor and a CDN vendor to work out whey they no longer allow network communication between their two sites, for example.

These operations faults are already captured in the 5th DORA metric, Reliability.

So, I'd encourage:

1. The rename for recovery from failed deployments, and
2. Hoepfully we can add operational performance (reliability) at some point soon

**Comment by ryanclark2** [comment]
Hello, chiming in to call out that failed deployments can mean the code or change didn't make it to production. The brief description helps clear things up, but the name itself might throw folks off.
