### ISSUE TITLE
Alignment issues on quick check recommendations

### ISSUE THREAD

**Issue by nathenharvey** [dora-team/dora.dev#474]
The older versions of the quick check include some copy that should probably be centered in the card tiles.

Example URLs:

elite - https://dora.dev/quickcheck/2019/results/?leadtime=5&deployfreq=4&chgfail=6&ttr=6&industry=government
high - https://dora.dev/quickcheck/2019/results/?leadtime=5&deployfreq=4&chgfail=6&ttr=3&industry=government
medium - https://dora.dev/quickcheck/2019/results/?leadtime=5&deployfreq=4&chgfail=5&ttr=3&industry=government
low - https://dora.dev/quickcheck/2019/results/?leadtime=2&deployfreq=4&chgfail=5&ttr=3&industry=government

![elite](https://github.com/dora-team/dora.dev/assets/16093/856a898a-d3c5-4989-b039-5e79f8bf88d3)
![high](https://github.com/dora-team/dora.dev/assets/16093/137b9892-ca07-44b0-ae1e-ec438f6872c5)
![low](https://github.com/dora-team/dora.dev/assets/16093/30243f61-49b6-459d-bc89-dbd75eada29f)
![medium](https://github.com/dora-team/dora.dev/assets/16093/934d0960-8e92-4c5d-a6ad-597970f0efda)

**Comment by davidstanke** [comment]
Thanks for the detailed bug report! This is fixed by #476
