### ISSUE TITLE
Link to Overall Research Program in Accelerate (p. 232) returns 404

### ISSUE THREAD

**Issue by yhoiseth** [dora-team/dora.dev#537]
Forsgren PhD, Nicole; Humble, Jez; Kim, Gene. Accelerate (p. 232). IT Revolution Press. Kindle Edition, page 232:

On page 232, there’s a link to https://bit.ly/high-perf-behaviors-practices, which leads to https://dora.dev/assets/transformation_practices.pdf, but that returns 404:

![Screenshot 2024-02-05 at 15 59 20](https://github.com/dora-team/dora.dev/assets/8469540/98a2e341-5d91-4a72-9597-166ce67ded7d)

**Comment by davidstanke** [comment]
Thank you for letting us know! We're working to track down that file and repost it to dora.dev. Meanwhile, you can find similar materials at dora.dev/research, or by viewing the "Structural Equation Models" tab of each year's page of [research archives](https://dora.dev/research/#dora_research_archives).
