### ISSUE TITLE
Add headings and links for each SEM in 2023

### ISSUE THREAD

**Issue by michelleirvine** [dora-team/dora.dev#538]
We have six diagrams on this page for 2023: https://dora.dev/research/2023/structural-equation-models/

Would be great to have a heading for each SEM, and be able to link to the heading. So that you can deep link to a specific diagram. Similar to how we can link to the questions: https://dora.dev/research/2023/questions/#artificial-intelligence

**Comment by davidstanke** [comment]
Great idea! Here's a PR for your review: #542
