### ISSUE TITLE
Bulleted text always appears bold

### ISSUE THREAD

**Issue by nathenharvey** [dora-team/dora.dev#563]
Bulleted text appears bold, or nearly bold.  As a result, bold copy in the bulleted text does not stand out and, when there are a lot of bullets, it can be difficlut to read the copy.

![image](https://github.com/dora-team/dora.dev/assets/16093/50a26841-351a-4806-b276-30d53ab78321)

**Comment by davidstanke** [comment]
Good call -- on it.
