### ISSUE TITLE
 Sponsor page should not link to the resource center

### ISSUE THREAD

**Issue by nathenharvey** [dora-team/dora.dev#595]
https://dora.dev/sponsors/ currently links to the Sponsor Resource Center but should not.

A quick fix would be to move the resource center to be a peer of `sponsors` but that doesn't feel quite right.

![CleanShot 2024-04-26 at 23 09 11](https://github.com/dora-team/dora.dev/assets/16093/b657819d-92dc-4dcf-80a2-5d6d7b304e84)

**Comment by davidstanke** [comment]
Fixed by #596
