### ISSUE TITLE
quickcheck.js is missing

### ISSUE THREAD

**Issue by ayang-waelder** [dora-team/dora.dev#687]
On the page https://dora.dev/quickcheck/ the questionnaire is missing:
![image](https://github.com/user-attachments/assets/73fecad2-a7db-4f64-a7ac-70df21648a1a)

The cause for this seems to be a missing file:
![image](https://github.com/user-attachments/assets/b7b2087b-bb83-4fb4-8306-a2d24c2c4a31)

The latest WaybackMachine snapshot (Jul 17) seems to be fine

**Comment by nathenharvey** [comment]
Thank you for reporting this @ayang-waelder! 

Are you still seeing the issue when visiting https://dora.dev/quickcheck?

It seems to be working for me at the moment. I wonder if it is a cache or browser issue? If it is still failing to load properly for you please try resetting the cache in your browser and trying again.

Please report back here once you've had a chance to try again. If it continues to fail, please share browser details (browser, version, OS, etc.)

Thanks!
Nathen

**Comment by ayang-waelder** [comment]
Hi Nathen,

I just checked and the site is working for me.
Whatever the issue was, it must've sorted itself out 😛

Thanks for reaching out!
