### ISSUE TITLE
Error on DORA Quick Check Questionnaire 

### ISSUE THREAD

**Issue by bgreen2909** [dora-team/dora.dev#819]
DORA QuickCheck Deploy Frequency question repeats the word "day"

"Between once per hour and once per day **day**"
<img width="977" alt="Screenshot 2024-11-05 at 10 05 34" src="https://github.com/user-attachments/assets/d75063ef-5de4-4441-8110-23646b590764">

**Comment by nathenharvey** [comment]
Thanks for reporting this, @bgreen2909!
