### ISSUE TITLE
Explore js frameworks

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#83]
Something like https://alpinejs.dev/ might be useful for the quickcheck, without being overwhelming (which I fear a full-on framework like React might be).

**Comment by davidstanke** [comment]
Alternatively, we might use a lightweight framework for elements outside the quickcheck (e.g. functionality like #19), and invest in a fully featured framework for the quickcheck as we iterate on it.

(Double-alternatively, per discussion with @jessegduke elsewhere, we might consider a light rewrite of the quickcheck as an intermediate step… a lightweight framework is likely as easy or easier to migrate to a full framework when appropriate than the current vanilla JS implementation will be)

**Comment by davidstanke** [comment]
Oh, also! Whatever decisions we make w/r/t js frameworks should be documented in the `/adrs` folder

**Comment by jessegduke** [comment]
Will do.  I hope to have a formal "recommendation" soon.  After we align, I will return to the other branch and issues to bring in alignment and subsequent PR.  Thanks!

**Comment by jessegduke** [comment]
Added AlpineJS Proposal for consideration in ADR in [adrs/use-alpineJS-for-light-weight-JS-framework.md](/dora-team/dora.dev/blob/main/adrs/use-alpineJS-for-light-weight-JS-framework.md)

**Comment by davidstanke** [comment]
Closed via #192
